#!/usr/bin/python

import optparse
from rdflib.sparql.sparqlGraph import SPARQLGraph as Graph
from rdflib.sparql import GraphPattern
from rdflib import URIRef, Literal, BNode, Namespace, FileInputSource
from rdflib import RDF, RDFS

from gasuse import DC, DATE, GAS, DOLLAR, MILE, GALLON

store = Graph()
store.parse(FileInputSource(open("gas.rdf")))

knownNames = store.query("?shortName",
                         GraphPattern([
    ("?station", RDFS.Class, GAS['station']),
    ("?station", GAS['shortName'], "?shortName"),
    ("?station", GAS['shortAddress'], "?shortAddress"),
    ]))

print "known stations:",
for name in knownNames:
    res = store.query("?station",
                      GraphPattern([("?station", GAS['shortName'], name)]))
    print "%s (%d)," % (name, len(res)),
print

#print "%d known stations: %s" % (len(knownStations), 
